init:
  - set PATH=C:/Ruby%ruby_version%/bin;c:/Program Files/Git/cmd;c:/Windows/system32;C:/Windows/System32/WindowsPowerShell/v1.0;C:/Program Files/Mercurial
  - set RUBYOPT=--verbose
install:
  - ps: |
      if ($env:RUBYDOWNLOAD -ne $null) {
        $(new-object net.webclient).DownloadFile("https://github.com/oneclick/rubyinstaller2/releases/download/rubyinstaller-head/rubyinstaller-head-$env:RUBYDOWNLOAD.exe", "$pwd/ruby-setup.exe")
        cmd /c ruby-setup.exe /verysilent /dir=C:/Ruby$env:ruby_version
      }
  - ruby --version
  - gem --version
  - gem install bundler --conservative
  - bundle install
  - ps: |
      if ($env:PGVERSION -ne $null)
      {
        $(new-object net.webclient).DownloadFile('http://get.enterprisedb.com/postgresql/postgresql-' + $env:PGVERSION + '.exe', 'C:/postgresql-setup.exe')
        cmd /c "C:/postgresql-setup.exe" --mode unattended --extract-only 1
      }
      $env:RUBY_DLL_PATH = 'C:/Program Files/PostgreSQL/' + $env:PGVER + '/bin;C:/Program Files (x86)/PostgreSQL/' + $env:PGVER + '/bin'
      $env:PATH = 'C:/Program Files/PostgreSQL/' + $env:PGVER + '/bin;' + $env:PATH
      $env:PATH = 'C:/Program Files (x86)/PostgreSQL/' + $env:PGVER + '/bin;' + $env:PATH
build_script:
  - bundle exec rake -rdevkit compile
test_script:
  - bundle exec rake test
environment:
  matrix:
    - ruby_version: "head"
      RUBYDOWNLOAD: x64
      PGVERSION: 11.1-1-windows-x64
      PGVER: 11
    - ruby_version: "head"
      RUBYDOWNLOAD: x86
      PGVERSION: 10.6-1-windows
      PGVER: 10
    - ruby_version: "24-x64"
      PGVERSION: 11.1-1-windows-x64
      PGVER: 11
    - ruby_version: "24"
      PGVERSION: 10.6-1-windows
      PGVER: 10
    - ruby_version: "22"
      PGVERSION: 9.3.25-1-windows
      PGVER: 9.3
    - ruby_version: "22-x64"
      PGVER: 9.6
matrix:
  allow_failures:
    - ruby_version: "head"
